In [ ]:
import numpy as np                                      

In [4]:
np.__version__

'1.26.4'

In [5]:
a=np.array([2,3,1])

In [8]:
a

array([2, 3, 1])

In [9]:
a.ndim

1

In [10]:
a.shape

(3,)

In [12]:
b=np.array([[1,3,4],[4,5,6]])

In [13]:
b

array([[1, 3, 4],
       [4, 5, 6]])

In [14]:
b.ndim

2

In [15]:
b.shape

(2, 3)

In [26]:
c=np.array([[[1,2,3],[4,5,6],[7,8,4]]])

In [20]:
c.ndim

3

In [21]:
c.shape

(1, 3, 3)

In [22]:
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
d=np.array([[[[1,2,3],[2,3,4],[5,6,4]]]])

In [31]:
d.ndim

4

In [33]:
d.shape

(1, 1, 3, 3)

In [45]:
e=np.array([[[[[1,2,3],[2,3,4],[5,6,4]]]]])
print(e)

[[[[[1 2 3]
    [2 3 4]
    [5 6 4]]]]]


In [37]:
e.ndim

5

In [38]:
e.shape

(1, 1, 1, 3, 3)

In [55]:
f=np.array([[[1,2,3,4,5],[2,9,4,5,6],[3,4,2,4,2]]])
print(f)
print(f[0][2][1])

[[[1 2 3 4 5]
  [2 9 4 5 6]
  [3 4 2 4 2]]]
4


In [57]:
arr=np.array(["a","b","c"])


In [58]:
arr.dtype

dtype('<U1')

In [62]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [63]:
x_new=x.reshape(4,3)

In [64]:
x_new

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
arr2=np.array([[1,2,3],[4,5,6,]])
arr2.ndim

2

In [67]:
newarray2=arr2.reshape(-1)
print(newarray2)

[1 2 3 4 5 6]


In [71]:
arr3=np.array([[1,2,3],[6,7,8]])

In [77]:
for i in arr3:
    for j in i:
        print(j)

1
2
3
6
7
8


In [78]:
arr4=np.array([[[1,2,3],[6,7,8],[3,5,1]]])

In [79]:
for i in arr4:
    for j in i:
        for k in j:
            print(k)

1
2
3
6
7
8
3
5
1


In [80]:
from numpy import random
x=random.randint(100)
x

76

In [81]:
import numpy as np

random_array = np.random.rand(2, 3)
print(random_array)

[[0.70022551 0.72392292 0.11619434]
 [0.61011882 0.25801289 0.94489684]]


In [97]:
from numpy import random
arr5=random.randint((1),size=(3,3))
arr5

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
from numpy import random
c=(1,1)
arr5=random.choice((c),size=(1,3,3))
arr5

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [104]:
import numpy as np
p=np.ones((3,3))
p

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [109]:
import numpy as np
d=np.array([[2,4,6],[8,2,6]])
d=d/2
d

array([[1., 2., 3.],
       [4., 1., 3.]])

In [121]:
import numpy as np
w=np.array([[2,4,6,2,31,3,2],[8,2,6,2,3,1,5]])
for i in w:
    for j in range(0,len(i),2):
        print(i[j])


2
6
31
2
8
6
3
5


In [ ]:
import numpy as np